import RiemannComparatorSolution.MellinAPI
import RiemannFormal.Analysis.FixedDetectorConsumer

#print axioms Comparator.MellinAPI.fixedMellinConsumerSolution
#print axioms RiemannFormal.Analysis.fixedDetector_negativeMass_implies_RH
