#!/usr/bin/env python3
"""Exact finite checks for attack2_theta.md; no analytic bound is tested.

All arithmetic is integral, including Gauss sums in Z[zeta_(6q)].
The two split ideals are generated by -2-3*omega and 1-3*omega.
Their residue embeddings send omega to 4 mod 7 and 9 mod 13.
Checks remain active under python -O.
"""
from __future__ import annotations

import argparse
from collections import Counter
from functools import lru_cache
from hashlib import sha256
import json
from math import gcd
from pathlib import Path


COUNTS = Counter()
PRIMES = (
    {"q": 7, "omega": 4, "generator": (-2, -3)},
    {"q": 13, "omega": 9, "generator": (1, -3)},
)


def check(group, truth, context):
    COUNTS[group] += 1
    if not truth:
        raise ArithmeticError(f"{group}: {context}")


def trim(poly):
    poly = list(poly)
    while len(poly) > 1 and poly[-1] == 0:
        poly.pop()
    return tuple(poly)


def monic_div_exact(numerator, denominator):
    numerator = list(trim(numerator))
    denominator = trim(denominator)
    if denominator[-1] != 1:
        raise ArithmeticError("polynomial divisor must be monic")
    quotient = [0] * max(1, len(numerator) - len(denominator) + 1)
    while len(numerator) >= len(denominator):
        offset = len(numerator) - len(denominator)
        value = numerator[-1]
        quotient[offset] = value
        for i, coef in enumerate(denominator):
            numerator[offset + i] -= value * coef
        numerator = list(trim(numerator))
        if numerator == [0]:
            break
    if any(numerator):
        raise ArithmeticError("cyclotomic polynomial division was not exact")
    return trim(quotient)


@lru_cache(None)
def cyclotomic(n):
    value = [-1] + [0] * (n - 1) + [1]
    for divisor in range(1, n):
        if n % divisor == 0:
            value = monic_div_exact(value, cyclotomic(divisor))
    return tuple(value)


class Cyclotomic:
    """The exact quotient Z[X]/Phi_n(X), with canonical coefficient vectors."""

    def __init__(self, n):
        self.n = n
        self.modulus = cyclotomic(n)
        self.degree = len(self.modulus) - 1
        self.zero = (0,) * self.degree
        self.one = (1,) + (0,) * (self.degree - 1)
        self.powers = [self.one]
        for _ in range(1, n):
            values = [0] + list(self.powers[-1])
            leading = values.pop()
            if leading:
                values = [
                    value - leading * self.modulus[i]
                    for i, value in enumerate(values)
                ]
            self.powers.append(tuple(values))

    def root(self, exponent):
        return self.powers[exponent % self.n]

    def scalar(self, value):
        return (value,) + (0,) * (self.degree - 1)

    def add(self, a, b):
        return tuple(x + y for x, y in zip(a, b))

    def scale(self, a, value):
        return tuple(value * x for x in a)

    def multiply(self, a, b):
        values = [0] * (2 * self.degree - 1)
        for i, x in enumerate(a):
            if x:
                for j, y in enumerate(b):
                    if y:
                        values[i + j] += x * y
        for degree in range(len(values) - 1, self.degree - 1, -1):
            leading = values[degree]
            if leading:
                offset = degree - self.degree
                for j, coef in enumerate(self.modulus):
                    values[offset + j] -= leading * coef
        return tuple(values[:self.degree])

    def sum_roots(self, exponents):
        out = [0] * self.degree
        for exponent in exponents:
            for i, value in enumerate(self.root(exponent)):
                out[i] += value
        return tuple(out)


def eis_multiply(z, w):
    a, b = z
    c, d = w
    return a * c - b * d, a * d + b * c - b * d


def eis_norm(z):
    a, b = z
    return a * a - a * b + b * b


def residue(z, prime):
    return (z[0] + z[1] * prime["omega"]) % prime["q"]


def character_log(value, prime):
    """Exponent of the physical zeta_6=1+omega; None means the local zero."""
    q = prime["q"]
    if value % q == 0:
        return None
    sixth_root = pow(value % q, (q - 1) // 6, q)
    zeta = (1 + prime["omega"]) % q
    for j in range(6):
        if pow(zeta, j, q) == sixth_root:
            return j
    raise ArithmeticError("sextic value did not lie in the physical root group")


def character_power(value, prime, exponent, ring):
    j = character_log(value, prime)
    if j is None:
        # This includes exponent zero for a present prime.
        return ring.zero
    return ring.root((ring.n // 6) * j * exponent)


def gauss(generator, factors, j, ring):
    q = eis_norm(generator)
    b = generator[1]
    exponents = []
    for t in range(q):
        logs = [character_log(t, prime) for prime in factors]
        if any(value is None for value in logs):
            continue
        # e(t/generator)=exp(2*pi*i*(-b)*t/q), exactly.
        exponents.append(
            (ring.n // 6) * j * sum(logs)
            + (ring.n // q) * (-b) * t
        )
    return ring.sum_roots(exponents)


def verify_native_gauss():
    combined = eis_multiply(PRIMES[0]["generator"], PRIMES[1]["generator"])
    check("eisenstein_norms", eis_norm(combined) == 91, combined)
    check("eisenstein_norms", eis_multiply((1, 2), (1, 2)) == (-3, 0), "lambda^2")
    check("eisenstein_norms", eis_norm((9, 0)) == 81, "N(lambda^4)")
    for prime in PRIMES:
        q = prime["q"]
        w = prime["omega"]
        generator = prime["generator"]
        check("native_prime_ideals", eis_norm(generator) == q, generator)
        check("native_prime_ideals", generator[0] % 3 == 1 and generator[1] % 3 == 0, "primary")
        check("native_prime_ideals", (w*w+w+1) % q == 0, "omega embedding")
        check("native_prime_ideals", residue(generator, prime) == 0, "ideal generator")
        check("native_prime_ideals", len({pow(1+w, j, q) for j in range(6)}) == 6, "primitive sixth root")
    panels = []
    for generator, factors in (
        (PRIMES[0]["generator"], (PRIMES[0],)),
        (PRIMES[1]["generator"], (PRIMES[1],)),
        (combined, PRIMES),
    ):
        q = eis_norm(generator)
        ring = Cyclotomic(6*q)
        g2 = gauss(generator, factors, 2, ring)
        g4 = gauss(generator, factors, 4, ring)
        check("conjugate_cubic_gauss", ring.multiply(g2, g4) == ring.scalar(q), q)
        check("adversarial_mobius_sign", ring.multiply(g2, g4) != ring.scalar(-q), q)
        panels.append({"norm": q, "cyclotomic_order": 6*q, "degree": ring.degree,
                       "unnormalized_G2_times_G4": q})

    ring = Cyclotomic(546)
    phase_log = 4 * (
        character_log(residue(PRIMES[1]["generator"], PRIMES[0]), PRIMES[0])
        + character_log(residue(PRIMES[0]["generator"], PRIMES[1]), PRIMES[1])
    )
    phase = ring.root((ring.n // 6) * phase_log)
    local_product = ring.multiply(
        gauss(PRIMES[0]["generator"], (PRIMES[0],), 4, ring),
        gauss(PRIMES[1]["generator"], (PRIMES[1],), 4, ring),
    )
    direct = gauss(combined, PRIMES, 4, ring)
    check("gauss_crt_phase", direct == ring.multiply(local_product, phase), phase_log % 6)
    check("adversarial_crt_phase", phase != ring.one and direct != local_product, "CRT phase cannot be dropped")
    return {"gauss_panels": panels, "CRT_cross_phase_zeta6_exponent": phase_log % 6}


def scalar_character_part(prime, j, denominator_quotient, ring):
    q = prime["q"]
    lam = (1 + 2 * prime["omega"]) % q
    sigma = pow(lam, 2, q) * denominator_quotient % q
    epsilon = -pow((pow(lam, 5, q) * denominator_quotient**2) % q, -1, q) % q
    result = character_power(sigma, prime, -2, ring)
    if j != 4:
        exponent = -2 if j == 0 else -j-2
        result = ring.multiply(result, character_power(epsilon, prime, exponent, ring))
    return result


def verify_scalar_scaling_and_masks():
    ring = Cyclotomic(6)
    for prime in PRIMES:
        q = prime["q"]
        for j in range(6):
            for denominator_quotient in range(1, q):
                before = scalar_character_part(prime, j, denominator_quotient, ring)
                for a in range(1, q):
                    after = scalar_character_part(prime, j, denominator_quotient*a % q, ring)
                    expected = ring.multiply(before, character_power(a, prime, 2*j+2, ring))
                    check("local_scalar_scaling", after == expected, (q, j, denominator_quotient, a))
        for valuation in range(1, 19):
            j = valuation % 6
            for active in ((False, True) if j == 0 else (True,)):
                for a in range(q):
                    direct = character_power(a, prime, valuation, ring)
                    if active:
                        direct = ring.multiply(direct, character_power(a, prime, 4, ring))
                        direct = ring.multiply(direct, character_power(a, prime, 2*j+2, ring))
                    expected = character_power(a, prime, 3*valuation, ring)
                    check("outer_quadratic_charge", direct == expected, (q, valuation, active, a))
        check("positive_sixth_power_zero", character_power(0, prime, 6, ring) == ring.zero, q)
        check("present_j0_zero", character_power(0, prime, 0, ring) == ring.zero, q)
        check("adversarial_local_zero", character_power(0, prime, 6, ring) != ring.one, q)
        # d^2 disappears only together with its exact nonunit mask.
        for d in range(q):
            for em in range(q):
                lhs = character_power(d*d*em, prime, 3, ring)
                rhs = ring.zero if d == 0 else character_power(em, prime, 3, ring)
                check("quadratic_divisor_mask", lhs == rhs, (q, d, em))


def mobius_squarefree(n):
    parity = 0
    divisor = 2
    while divisor*divisor <= n:
        if n % divisor == 0:
            n //= divisor
            parity += 1
            if n % divisor == 0:
                return 0
        divisor += 1
    parity += int(n > 1)
    return -1 if parity % 2 else 1


def verify_ramanujan():
    combined = eis_multiply(PRIMES[0]["generator"], PRIMES[1]["generator"])
    panels = []
    for generator in (PRIMES[0]["generator"], PRIMES[1]["generator"], combined):
        q = eis_norm(generator)
        b = generator[1]
        ring = Cyclotomic(6*q)
        units = [y for y in range(q) if gcd(y, q) == 1]
        residues = []
        for x in range(q):
            direct = ring.sum_roots((ring.n//q)*(-b)*x*y for y in units)
            ramanujan = sum(
                divisor * mobius_squarefree(q//divisor)
                for divisor in range(1, q+1) if q % divisor == 0 and x % divisor == 0
            )
            check("complete_native_ramanujan", direct == ring.scalar(ramanujan), (q, x))
            residues.append(ramanujan)
        check("ramanujan_mean_zero", sum(residues) == 0, q)
        check("ramanujan_energy", sum(value*value for value in residues) == q*len(units), q)
        panels.append({"norm": q, "complete_residue_count": q,
                       "sum_ramanujan": sum(residues),
                       "sum_ramanujan_squared": sum(value*value for value in residues),
                       "N_times_phi": q*len(units)})
    return panels


def verify_local_euler_correction():
    ring = Cyclotomic(6)
    degree = 12
    for prime in PRIMES:
        q = prime["q"]
        for value in range(q):
            tau = character_power(value, prime, 1, ring)
            # In 1/L*(1+(q-1)tau*z)/(1-tau*z), the correction's
            # positive-degree coefficient is q*tau^n.
            correction = [ring.one] + [
                ring.scale(character_power(value, prime, n, ring), q)
                for n in range(1, degree+1)
            ]
            for n in range(degree+1):
                reconstructed = correction[n]
                if n:
                    reconstructed = ring.add(
                        reconstructed, ring.scale(ring.multiply(tau, correction[n-1]), -1)
                    )
                expected = ring.one if n == 0 else (
                    ring.scale(tau, q-1) if n == 1 else ring.zero
                )
                check("local_euler_correction", reconstructed == expected, (q, value, n))
    return {"formal_degree": degree, "includes_tau_zero": True}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    native = verify_native_gauss()
    verify_scalar_scaling_and_masks()
    ramanujan = verify_ramanujan()
    euler = verify_local_euler_correction()
    result = {
        "status": "PASS",
        "scope": "Exact finite arithmetic only; no automorphy, convergence, zero-free region, or moment inequality is tested.",
        "source_sha256": sha256(Path(__file__).read_bytes()).hexdigest(),
        "assertions_total": sum(COUNTS.values()),
        "assertions_by_category": dict(sorted(COUNTS.items())),
        "native_ideals": list(PRIMES),
        **native,
        "ramanujan_panels": ramanujan,
        "local_euler_correction": euler,
    }
    args.output.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    print(json.dumps({"status": result["status"], "assertions_total": result["assertions_total"],
                      "source_sha256": result["source_sha256"], "output": str(args.output)},
                     sort_keys=True))


if __name__ == "__main__":
    main()
