import OAI.NumberTheory.CubicMoment.Theta.CubicThetaKubotaInteger

namespace OAI

/-! The manuscript's group Gamma_2 generated by Gamma_1(3) and SL(2,Z).
Normality of the principal group gives a concrete two-factor description. -/
noncomputable section
open scoped MatrixGroups
namespace CubicFirstMoment

def cubicThetaExtendedGroup : Subgroup SL(2,Eisenstein) where
  carrier := {g | ∃ n : cubicThetaPrincipalGroup, ∃ u : SL(2,ℤ),
    g = n.val*cubicThetaIntegerEmbedding u}
  one_mem' := ⟨1,1,by simp⟩
  mul_mem' := by
    rintro g h ⟨n,u,rfl⟩ ⟨m,v,rfl⟩
    refine ⟨n*cubicThetaKubotaConjugate (cubicThetaIntegerEmbedding u) m,u*v,?_⟩
    simp [cubicThetaKubotaConjugate,mul_assoc]
  inv_mem' := by
    rintro g ⟨n,u,rfl⟩
    refine ⟨cubicThetaKubotaConjugate (cubicThetaIntegerEmbedding u⁻¹) n⁻¹,u⁻¹,?_⟩
    simp [cubicThetaKubotaConjugate,mul_assoc]

theorem cubicThetaExtendedGroup_eq_sup : cubicThetaExtendedGroup =
    cubicThetaPrincipalGroup ⊔ cubicThetaIntegerEmbedding.range := by
  apply le_antisymm
  · rintro g ⟨n,u,rfl⟩
    have hN : cubicThetaPrincipalGroup ≤
        cubicThetaPrincipalGroup ⊔ cubicThetaIntegerEmbedding.range := le_sup_left
    have hI : cubicThetaIntegerEmbedding.range ≤
        cubicThetaPrincipalGroup ⊔ cubicThetaIntegerEmbedding.range := le_sup_right
    exact mul_mem (hN n.property) (hI ⟨u,rfl⟩)
  · apply sup_le
    · intro n hn
      exact ⟨⟨n,hn⟩,1,by simp⟩
    · rintro g ⟨u,rfl⟩
      exact ⟨1,u,by simp⟩

def cubicThetaExtendedPrincipal (g : cubicThetaExtendedGroup) : cubicThetaPrincipalGroup :=
  Classical.choose g.property

def cubicThetaExtendedInteger (g : cubicThetaExtendedGroup) : SL(2,ℤ) :=
  Classical.choose (Classical.choose_spec g.property)

lemma cubicThetaExtended_decomposition (g : cubicThetaExtendedGroup) :
    g.val = (cubicThetaExtendedPrincipal g).val*
      cubicThetaIntegerEmbedding (cubicThetaExtendedInteger g) :=
  Classical.choose_spec (Classical.choose_spec g.property)

def cubicThetaPrincipalInclusion : cubicThetaPrincipalGroup →* cubicThetaExtendedGroup where
  toFun n := ⟨n.val,⟨n,1,by simp⟩⟩
  map_one' := rfl
  map_mul' _ _ := rfl

def cubicThetaIntegerInclusion : SL(2,ℤ) →* cubicThetaExtendedGroup where
  toFun u := ⟨cubicThetaIntegerEmbedding u,⟨1,u,by simp⟩⟩
  map_one' := Subtype.ext (map_one _)
  map_mul' u v := Subtype.ext (map_mul _ u v)

end CubicFirstMoment

end

end OAI
