"""Exact finite reconstruction for pass3. Bounded algebra is not an analytic proof.
The six actual source signs are independently regenerated by source_moments.py.
All acceptance tests survive Python -O. Standard library only.
"""
from dataclasses import dataclass
from fractions import Fraction as F
from math import comb, factorial
from pathlib import Path
import argparse, hashlib, json, unittest
import source_moments as sm

@dataclass(frozen=True)
class Q:
    re:F=F(0)
    im:F=F(0)
    def __post_init__(self):
        if isinstance(self.re,(float,bool)) or isinstance(self.im,(float,bool)):
            raise TypeError('exact rational coordinates required')
        object.__setattr__(self,'re',F(self.re));object.__setattr__(self,'im',F(self.im))
    @staticmethod
    def of(x):return x if isinstance(x,Q) else Q(x)
    def __add__(self,x):
        x=self.of(x);return Q(self.re+x.re,self.im+x.im)
    __radd__=__add__
    def __neg__(self):return Q(-self.re,-self.im)
    def __sub__(self,x):return self+-self.of(x)
    def __rsub__(self,x):return self.of(x)+-self
    def __mul__(self,x):
        x=self.of(x);return Q(self.re*x.re-self.im*x.im,self.re*x.im+self.im*x.re)
    __rmul__=__mul__
    def conj(self):return Q(self.re,-self.im)
    def norm2(self):return self.re**2+self.im**2
    def __truediv__(self,x):
        x=self.of(x);d=x.norm2()
        if not d:raise ZeroDivisionError('Gaussian rational zero')
        v=self*x.conj();return Q(v.re/d,v.im/d)
    def __rtruediv__(self,x):return self.of(x)/self
    def __pow__(self,n):
        if type(n)is not int or n<0:raise ValueError('nonnegative integer power')
        out=Q(1)
        for _ in range(n):out*=self
        return out
    def __bool__(self):return bool(self.re or self.im)
I=Q(0,1)

def lag(n):
    if type(n)is not int or n<0:raise ValueError('nonnegative integer degree')
    return [F((-1)**j*comb(n,j),factorial(j)) for j in range(n+1)]
def val(p,x):
    out=F(0)
    for a in reversed(p):out=out*x+a
    return out
def derivative(p):return [j*p[j] for j in range(1,len(p))] or [F(0)]
def pmul(p,q):
    out=[F(0)]*(len(p)+len(q)-1)
    for i,a in enumerate(p):
        for j,b in enumerate(q):out[i+j]+=a*b
    return out
def integral(p):return sum((a*factorial(j) for j,a in enumerate(p)),F(0))
def matmul(a,b):
    if not a or not b or len(a[0])!=len(b):raise ValueError('matrix shape')
    return [[sum((a[i][k]*b[k][j] for k in range(len(b))),F(0))
             for j in range(len(b[0]))] for i in range(len(a))]
def inv(a):
    n=len(a)
    if not n or any(len(r)!=n for r in a):raise ValueError('square matrix')
    b=[r[:]+[F(int(i==j)) for j in range(n)] for i,r in enumerate(a)]
    for i in range(n):
        p=next((j for j in range(i,n) if b[j][i]),None)
        if p is None:raise ValueError('singular matrix')
        b[i],b[p]=b[p],b[i];v=b[i][i];b[i]=[x/v for x in b[i]]
        for j in range(n):
            if j!=i:
                v=b[j][i];b[j]=[x-v*y for x,y in zip(b[j],b[i])]
    return [r[n:] for r in b]

def boundary(panel,n):
    out=[Q()]*(n+1);b=F(3,2)
    for z,mult in panel:
        z2=z*z;d0=4+z2;d1=-2*z2;d2=z2;values=[]
        for j in range(n+1):
            num=(2 if j==0 else -2 if j==1 else 0)/(b*b+z2)
            if j>=1:num-=d1*values[j-1]
            if j>=2:num-=d2*values[j-2]
            values.append(num/d0);out[j]+=mult*values[j]
    return out

def feature(z,n):
    return 2/((F(3,2)-I*z)*(2-I*z)) * ((-I*z)/(2-I*z))**n

def finite_matrix(panel,n):
    c=boundary(panel,n-1);a=[[Q() for _ in range(n)] for _ in range(n)]
    for i in range(n):
        for j in range(n):
            rhs=2*(c[i] if j==0 else Q())+2*(c[j] if i==0 else Q())
            if i:rhs+=a[i-1][j]
            if j:rhs+=a[i][j-1]
            a[i][j]=rhs/2
    return a

class Check:
    def __init__(self):self.counts={}
    def __call__(self,g,condition):
        if not condition:raise ArithmeticError('failed control: '+g)
        self.counts[g]=self.counts.get(g,0)+1

def run(include_source=True):
    check=Check()
    for n in range(13):
        p=lag(n);dp=derivative(p)
        check('Laguerre_exact_integrals',integral(pmul(p,p))==1)
        check('Laguerre_exact_integrals',integral(pmul(dp,dp))==n)
        for x in [F(0),F(1,3),F(2),F(7,2)]:
            for y in [F(0),F(1,3),F(2),F(7,2)]:
                lhs=sum((val(lag(k),x)*val(lag(k),y) for k in range(n+1)),F(0))
                if x!=y:
                    rhs=(n+1)*(val(p,x)*val(lag(n+1),y)-val(lag(n+1),x)*val(p,y))/(x-y)
                else:
                    rhs=(n+1)*(val(lag(n+1),x)*val(dp,x)-val(p,x)*val(derivative(lag(n+1)),x))
                check('Christoffel_Darboux',lhs==rhs)
    for xs,ws in [([F(1,10),F(1,5),F(1,2)],[F(2,3),F(3,4),F(5,6)]),
                  ([F(1,7),F(2,7),F(4,7)],[F(3),F(2),F(1)])]:
        m=[sum((w*x**k for x,w in zip(xs,ws)),F(0)) for k in range(6)]
        H=[[m[i+j] for j in range(3)] for i in range(3)]
        Hp=[[m[i+j+1] for j in range(3)] for i in range(3)]
        J=matmul(inv(H),Hp);v=[[F(1)],[F(0)],[F(0)]]
        for k in range(6):
            check('weighted_quadrature',matmul(H,v)[0][0]==m[k]);v=matmul(J,v)
        for i in range(3):
            for j in range(3):check('weighted_quadrature',matmul(H,J)[i][j]==Hp[i][j])
    panels=[[(Q(1),1),(Q(-1),1)],
            [(Q(0,F(1,4)),1),(Q(0,F(-1,4)),1)],
            [(Q(x,y),3) for x in (F(-2),F(2)) for y in (F(-1,4),F(1,4))],
            [(Q(1),2),(Q(-1),2)]+[(Q(x,y),1) for x in (F(-3),F(3)) for y in (F(-1,3),F(1,3))]]
    for panel in panels:
        a=finite_matrix(panel,6)
        for i in range(6):
            for j in range(6):
                direct=sum((m*feature(z,i)*feature(z.conj(),j).conj() for z,m in panel),Q())
                check('Hardy_source_vs_feature_matrix',a[i][j]==direct)
                check('Hardy_source_vs_feature_matrix',a[i][j]==a[j][i] and a[i][j].im==0)
        for z,m in panel:
            alpha=(-I*z)/(2-I*z);beta=(-I*z.conj())/(2-I*z.conj())
            d=feature(z,0)*feature(z.conj(),0).conj()
            check('Hardy_geometric_trace',d/(1-alpha*beta.conj())==1/(F(9,4)+z*z))
            check('Hardy_feature_tail',alpha.norm2()<1)
            y=z.im;g=z.re
            check('Hardy_feature_tail',1-alpha.norm2()==4*(1+y)/(g*g+(2+y)**2))
            check('Hardy_feature_tail',1-alpha.norm2()>=2/(g*g+F(25,4)))
    a=finite_matrix(panels[1],2)
    check('negative_synthetic_control',(a[0][0]*a[1][1]-a[0][1]*a[1][0]).re<0)
    for beta in [F(1,4),F(1,2),F(3,4)]:
        for gamma in [F(1),F(5)]:
            rho=Q(beta,gamma);z=(rho-F(3,2))/(rho+F(1,2))
            check('Cayley_horizontal_identity',1-z.norm2()==4*(beta-F(1,2))/(rho+F(1,2)).norm2())
    check('positive_source_pole', (Q(1)-F(3,2))/(Q(1)+F(1,2))==Q(F(-1,3)))
    source=sm.certify() if include_source else None
    if source:
        for ok in source['checks'].values():check('actual_source_interval_signs',ok)
    return {'status':'PASS_THREE_ROUTE_PASS3','arithmetic':'EXACT_RATIONAL_AND_GAUSSIAN_RATIONAL',
      'checks':check.counts,'total':sum(check.counts.values()),'RH_proved':False,
      'analytic_theorems_machine_proved':False,'source_moments_included':bool(source)}

def canonical(x):return json.dumps(x,sort_keys=True,indent=2)+'\n'
def compare_text(text,expected):
    if text!=canonical(expected):raise ValueError('stored result mismatch')
MANIFEST_FILES = frozenset({
    'README.md', 'REVIEW_AND_SOURCES.md', 'R1_MOMENTS.md',
    'R2_MOBIUS_LAGUERRE.md', 'R3_LAGUERRE_CAPTURE.md',
    'source_moments.py', 'verify.py', 'regression.py',
    'MOMENTS.json', 'RESULTS.json', 'REGRESSION.json',
})

def hashes(root=None):
    root=Path(root) if root is not None else Path(__file__).resolve().parent
    seen=set()
    for line in (root/'SHA256SUMS').read_text().splitlines():
        h,name=line.split('  ',1)
        if name not in MANIFEST_FILES or name in seen:raise ValueError('manifest path/duplicate')
        if len(h)!=64 or any(c not in '0123456789abcdef' for c in h):raise ValueError('manifest digest')
        if not (root/name).is_file():raise ValueError('manifest missing file')
        if hashlib.sha256((root/name).read_bytes()).hexdigest()!=h:raise ValueError('manifest mismatch: '+name)
        seen.add(name)
    if seen!=MANIFEST_FILES:raise ValueError('manifest coverage')

class Tests(unittest.TestCase):
    def test_float_rejected(self):
        with self.assertRaises(TypeError):Q(0.1)
    def test_bool_rejected(self):
        with self.assertRaises(TypeError):Q(True)
    def test_zero_division(self):
        with self.assertRaises(ZeroDivisionError):Q(1)/Q()
    def test_negative_degree(self):
        with self.assertRaises(ValueError):lag(-1)
    def test_degree_alias(self):
        with self.assertRaises(ValueError):lag(True)
    def test_singular_matrix(self):
        with self.assertRaises(ValueError):inv([[F(0)]])
    def test_noninteger_source_argument(self):
        with self.assertRaises(ValueError):sm.zeta_series(2.0)
    def test_tiny_prefactor_not_prerounded(self):
        out=sm.scale([sm.Ball(10**30)],F(1,10**60))[0]
        self.assertEqual(out.lo,F(1,10**30));self.assertEqual(out.hi,F(1,10**30))
    def test_changed_result(self):
        with self.assertRaises(ValueError):compare_text('{"ok":false}\n',{'ok':True})
    def test_boolean_integer_alias(self):
        with self.assertRaises(ValueError):compare_text(canonical({'ok':1}),{'ok':True})

    def test_manifest_coverage(self):
        import tempfile
        with tempfile.TemporaryDirectory() as d:
            root=Path(d);(root/'SHA256SUMS').write_text('')
            with self.assertRaises(ValueError):hashes(root)
    def test_changed_proof_bytes(self):
        import tempfile
        with tempfile.TemporaryDirectory() as d:
            root=Path(d)
            for name in MANIFEST_FILES:(root/name).write_text('fixture')
            digest=hashlib.sha256(b'fixture').hexdigest()
            (root/'SHA256SUMS').write_text(''.join(digest+'  '+name+'\n' for name in sorted(MANIFEST_FILES)))
            hashes(root)
            (root/'R1_MOMENTS.md').write_text('changed proof')
            with self.assertRaises(ValueError):hashes(root)

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--write',action='store_true');p.add_argument('--tests',action='store_true');args=p.parse_args()
    if args.tests:
        suite=unittest.defaultTestLoader.loadTestsFromTestCase(Tests)
        result=unittest.TextTestRunner(verbosity=2).run(suite)
        raise SystemExit(0 if result.wasSuccessful() else 1)
    result=run();path=Path(__file__).with_name('RESULTS.json')
    if args.write:path.write_text(canonical(result))
    else:
        compare_text(path.read_text(),result)
        compare_text(Path(__file__).with_name('MOMENTS.json').read_text(),sm.certify())
        hashes()
    print(result['status']);print(result['total'],'distinct finite controls')
